name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^2.8.1
  mysql1: ^0.20.0
  password_dart: ^2.0.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
